# Generated by Django 3.2.5 on 2021-07-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='character_alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hero_alias',
            new_name='name',
        ),
    ]
